POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = custom
UNICODE_ENABLE = yes
BOOTMAGIC_ENABLE = no
EXTRAKEY_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
RGBLIGHT_ENABLE = no
LTO_ENABLE = yes


SRC += analog.c ./lib/logo_reader.c
