POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick
UNICODE_ENABLE = yes
BOOTMAGIC_ENABLE = no
EXTRAKEY_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
RGBLIGHT_ENABLE = no
LTO_ENABLE = yes


SRC += ./lib/logo_reader.c
