#pragma once

#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define QMK_KEYS_PER_SCAN 4
#define TAPPING_TERM 200

#define POINTING_DEVICE_CS_PIN GP14
#define SPI_SCK_PIN GP15
#define SPI_MOSI_PIN GP16
#define SPI_MISO_PIN GP17
